export const PLANETS = [
  {
    id: 'aurelia',
    name: 'Aurelia',
    subtitle: 'Golden cradle',
    position: [-310, 20, -430],
    radius: 42,
    color: 0xd69a4b,
    atmosphere: 0xffd28a,
    ground: 0x9b5f35,
    accent: 0xe7bd67,
    sky: 0x23152a,
    fog: 0x5f3442,
    seed: 11,
    civilization: 'The Aurelian Compact',
    civilizationCopy: 'Patient builders who shape sun-baked stone into resonant cities. They value shelter, steady power, and wide horizons.',
    resources: ['ferrite', 'carbon', 'crystal'],
  },
  {
    id: 'viridia',
    name: 'Viridia',
    subtitle: 'Emerald wilds',
    position: [430, -30, -250],
    radius: 49,
    color: 0x2f8b78,
    atmosphere: 0x7ef1c2,
    ground: 0x183f38,
    accent: 0x55c58f,
    sky: 0x071d24,
    fog: 0x16494a,
    seed: 29,
    civilization: 'The Mycelian Chorus',
    civilizationCopy: 'A communal people who cultivate luminous forests and exchange knowledge through living root networks.',
    resources: ['carbon', 'carbon', 'crystal'],
  },
  {
    id: 'vespera',
    name: 'Vespera',
    subtitle: 'Frozen twilight',
    position: [-520, 65, 360],
    radius: 37,
    color: 0x6a85b7,
    atmosphere: 0xb8dcff,
    ground: 0x52657c,
    accent: 0xa6d4e9,
    sky: 0x081224,
    fog: 0x334b6b,
    seed: 47,
    civilization: 'The Vesper Union',
    civilizationCopy: 'Engineers and navigators who build warm glass sanctuaries beneath permanent auroras.',
    resources: ['crystal', 'ferrite', 'crystal'],
  },
  {
    id: 'cinder',
    name: 'Cinder IX',
    subtitle: 'Volcanic frontier',
    position: [520, 110, 470],
    radius: 45,
    color: 0x7d3027,
    atmosphere: 0xff725c,
    ground: 0x241919,
    accent: 0xff6543,
    sky: 0x17070a,
    fog: 0x51211f,
    seed: 73,
    civilization: 'The Emberbound',
    civilizationCopy: 'Heat-hardened metallurgists seeking a permanent city beside the planet’s endless rivers of fire.',
    resources: ['ferrite', 'ferrite', 'crystal'],
  },
];

export const BUILDINGS = {
  extractor: {
    id: 'extractor',
    name: 'Mineral Extractor',
    symbol: '⟐',
    description: 'Passively produces ferrite while you explore.',
    cost: { ferrite: 18, carbon: 8 },
    color: 0xf0a95a,
  },
  refinery: {
    id: 'refinery',
    name: 'Fuel Refinery',
    symbol: '⌬',
    description: 'Converts carbon and crystal into launch fuel.',
    cost: { ferrite: 15, carbon: 10 },
    color: 0x62d9d1,
  },
  habitat: {
    id: 'habitat',
    name: 'Habitat Pod',
    symbol: '⬡',
    description: 'Shelters 12 settlers and grows a colony.',
    cost: { ferrite: 24, carbon: 18 },
    color: 0x8aa8ff,
  },
  beacon: {
    id: 'beacon',
    name: 'Colony Beacon',
    symbol: '◈',
    description: 'Found a new civilization on this world.',
    cost: { ferrite: 35, carbon: 22, crystal: 12 },
    color: 0xffcf6b,
  },
};

export const MISSIONS = [
  { title: 'First Contact', description: 'Approach a planet and land on its surface.', target: 1, key: 'landings' },
  { title: 'Local Materials', description: 'Mine 3 resource deposits with your ship.', target: 3, key: 'mined' },
  { title: 'A Full Tank', description: 'Build a refinery and synthesize starship fuel.', target: 1, key: 'refined' },
  { title: 'A Place to Begin', description: 'Deploy a colony beacon and welcome its settlers.', target: 1, key: 'colonies' },
  { title: 'Among the Stars', description: 'Visit and land on a second world.', target: 2, key: 'visited' },
];

export const RESOURCE_INFO = {
  ferrite: { label: 'Ferrite', color: 0xf5a65b, symbol: 'Fe', amount: [7, 13] },
  carbon: { label: 'Carbon', color: 0x4ee1a0, symbol: 'C', amount: [6, 12] },
  crystal: { label: 'Resonant Crystal', color: 0x9b8cff, symbol: 'Cr', amount: [4, 9] },
};
